copyright: Copyright (c) 2017, Stefan Wimmer
edit_uri: blob/master/docs/
extra:
    feature:
        tabs: true
    palette:
        primary: light blue
        accent: indigo
    social:
        -
            type: github
            link: https://github.com/stefanwimmer128
markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - extra
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
        separator: _
pages:
    - Home: index.md
    - Array operations:
        - "#concat": array/concat.md
        - "#each": array/each.md
        - "#filter": array/filter.md
        - "#find": array/find.md
        - "#flatten": array/flatten.md
        - "#map": array/map.md
        - "#mapKey": array/mapKey.md
        - "#reduce": array/reduce.md
        - "#reverse": array/reverse.md
        - "#shift": array/shift.md
    - Boolean operations:
        - "#invert": boolean/invert.md
    - Function operations:
        - "#processors": function/processors.md
    - Math operations:
        - "#sum": math/sum.md
    - Object operations:
        - "#extend": object/extend.md
        - "#withProperty": object/withProperty.md
    - Utils:
        - "#chain": utils/chain.md
repo_name: stefanwimmer128/core
repo_url: https://github.com/stefanwimmer128/core
site_description: A functional programmers dream
site_author: stefanwimmer128
site_name: "@stefanwimmer128/core"
site_url: https://stefanwimmer128.github.io/core
theme: material
